<?php
/**
 * TokenApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  ProductApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ProductApi\Test\Api;

use \ProductApi\Configuration;
use \ProductApi\ApiException;
use \ProductApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TokenApiTest Class Doc Comment
 *
 * @category Class
 * @package  ProductApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TokenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for postCredentialsItem
     *
     * .
     *
     */
    public function testPostCredentialsItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postRefreshToken
     *
     * .
     *
     */
    public function testPostRefreshToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
